output_frame_id: pico_flexx_depth_link
rate: 10
range_min: 0.3
range_max: 5.0
sensor_mount_height: 0.63
sensor_tilt_angle: 60.0

publish_depth: true
cam_model_update: false
used_depth_height: 170
used_depth_height_min: 0
block_size: 16
block_points_thresh: 3
depth_img_step_row: 8
depth_img_step_col: 8
inverted: true
ground_margin: 0.10
